### ISSUE TITLE
Just wanted to try it out for fun

### ISSUE THREAD

**Issue by strich3** [RealBauHD/minecraft-server#1]
![image](https://user-images.githubusercontent.com/56207893/207703359-8e671621-e7b7-4699-aa88-8cbfff100a51.png)
I'm stuck on this tho :D

**Comment by RealBauHD** [comment]
Yes in the 1.19.3 it somehow loads for a long time I have to check. The inventory was for testing xd

**Comment by strich3** [comment]
could be good for minigames
